name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches:
      - angular

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          path: ./
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        working-directory: ./thebccampaign
        with:
          persist-credentials: false
          
      - name: Change directory
        run: |
          cd ./thebccampaign
          pwd
      - name: Set up Node.js
        uses: actions/setup-node@v3
        working-directory: ./thebccampaign
        with:
          node-version: 16
          
      - name: Install dependencies
        run: npm install
        working-directory: ./thebccampaign
      - name: Build Angular app
        run: npm run build --prod
        working-directory: ./thebccampaign
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
